/*
 * Plan SW - Toepasbare regel SW
 *
 * Nog in te voorzien
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: robert.melskens@vng.nl
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// &lt;body&gt;&lt;p&gt;Is dit een definitie?&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;p&gt;Is dit een definitie?&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;ul&gt;&lt;li&gt;&#x60;MultiSurface&#x60; - GM_MultiSurface&lt;/li&gt;&lt;li&gt;&#x60;Surface&#x60; - GM_Surface&lt;/li&gt;&lt;li&gt;&#x60;MultiLineString&#x60; - GM_MultiLineString&lt;/li&gt;&lt;li&gt;&#x60;LineString&#x60; - GM_LineString&lt;/li&gt;&lt;li&gt;&#x60;MultiPoint&#x60; - GM_MultiPoint&lt;/li&gt;&lt;li&gt;&#x60;Point&#x60; - GM_Point&lt;/li&gt;&lt;/ul&gt;&lt;/body&gt;
    /// </summary>
    /// <value>&lt;body&gt;&lt;p&gt;Is dit een definitie?&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;p&gt;Is dit een definitie?&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;ul&gt;&lt;li&gt;&#x60;MultiSurface&#x60; - GM_MultiSurface&lt;/li&gt;&lt;li&gt;&#x60;Surface&#x60; - GM_Surface&lt;/li&gt;&lt;li&gt;&#x60;MultiLineString&#x60; - GM_MultiLineString&lt;/li&gt;&lt;li&gt;&#x60;LineString&#x60; - GM_LineString&lt;/li&gt;&lt;li&gt;&#x60;MultiPoint&#x60; - GM_MultiPoint&lt;/li&gt;&lt;li&gt;&#x60;Point&#x60; - GM_Point&lt;/li&gt;&lt;/ul&gt;&lt;/body&gt;</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum GeometrieType
    {
        /// <summary>
        /// Enum MultiSurface for value: MultiSurface
        /// </summary>
        [EnumMember(Value = "MultiSurface")]
        MultiSurface = 1,

        /// <summary>
        /// Enum Surface for value: Surface
        /// </summary>
        [EnumMember(Value = "Surface")]
        Surface = 2,

        /// <summary>
        /// Enum MultiLineString for value: MultiLineString
        /// </summary>
        [EnumMember(Value = "MultiLineString")]
        MultiLineString = 3,

        /// <summary>
        /// Enum LineString for value: LineString
        /// </summary>
        [EnumMember(Value = "LineString")]
        LineString = 4,

        /// <summary>
        /// Enum MultiPoint for value: MultiPoint
        /// </summary>
        [EnumMember(Value = "MultiPoint")]
        MultiPoint = 5,

        /// <summary>
        /// Enum Point for value: Point
        /// </summary>
        [EnumMember(Value = "Point")]
        Point = 6

    }

}
