/*
 * Plan SW - Toepasbare regel SW
 * Nog in te voorzien
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: robert.melskens@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.JuridischeRegelVoorIedereenHal;

/**
 * ActiviteitEmbedded
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-10T09:19:26.366Z[Etc/UTC]")
public class ActiviteitEmbedded {
  public static final String SERIALIZED_NAME_BIJBEHORENDE_JURIDISCHE_REGELS_VOOR_IEDEREEN = "bijbehorendeJuridischeRegelsVoorIedereen";
  @SerializedName(SERIALIZED_NAME_BIJBEHORENDE_JURIDISCHE_REGELS_VOOR_IEDEREEN)
  private List<JuridischeRegelVoorIedereenHal> bijbehorendeJuridischeRegelsVoorIedereen = null;


  public ActiviteitEmbedded bijbehorendeJuridischeRegelsVoorIedereen(List<JuridischeRegelVoorIedereenHal> bijbehorendeJuridischeRegelsVoorIedereen) {
    
    this.bijbehorendeJuridischeRegelsVoorIedereen = bijbehorendeJuridischeRegelsVoorIedereen;
    return this;
  }

  public ActiviteitEmbedded addBijbehorendeJuridischeRegelsVoorIedereenItem(JuridischeRegelVoorIedereenHal bijbehorendeJuridischeRegelsVoorIedereenItem) {
    if (this.bijbehorendeJuridischeRegelsVoorIedereen == null) {
      this.bijbehorendeJuridischeRegelsVoorIedereen = new ArrayList<>();
    }
    this.bijbehorendeJuridischeRegelsVoorIedereen.add(bijbehorendeJuridischeRegelsVoorIedereenItem);
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;Bij een regel die een activiteit vastlegt geeft deze relatie aan om welke activiteit het gaat. De bijbehorende locatie(s) waar het om gaat is/zijn bij de activiteit zelf te vinden.&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;p&gt;Een inhoudelijke toelichting op de toepassing van het informatie-element.&lt;/p&gt;&lt;/body&gt;
   * @return bijbehorendeJuridischeRegelsVoorIedereen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<body><p>Bij een regel die een activiteit vastlegt geeft deze relatie aan om welke activiteit het gaat. De bijbehorende locatie(s) waar het om gaat is/zijn bij de activiteit zelf te vinden.</p></body><body><p>Een inhoudelijke toelichting op de toepassing van het informatie-element.</p></body>")

  public List<JuridischeRegelVoorIedereenHal> getBijbehorendeJuridischeRegelsVoorIedereen() {
    return bijbehorendeJuridischeRegelsVoorIedereen;
  }


  public void setBijbehorendeJuridischeRegelsVoorIedereen(List<JuridischeRegelVoorIedereenHal> bijbehorendeJuridischeRegelsVoorIedereen) {
    this.bijbehorendeJuridischeRegelsVoorIedereen = bijbehorendeJuridischeRegelsVoorIedereen;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActiviteitEmbedded activiteitEmbedded = (ActiviteitEmbedded) o;
    return Objects.equals(this.bijbehorendeJuridischeRegelsVoorIedereen, activiteitEmbedded.bijbehorendeJuridischeRegelsVoorIedereen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bijbehorendeJuridischeRegelsVoorIedereen);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActiviteitEmbedded {\n");
    sb.append("    bijbehorendeJuridischeRegelsVoorIedereen: ").append(toIndentedString(bijbehorendeJuridischeRegelsVoorIedereen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

