/*
 * Plan SW - Toepasbare regel SW
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: robert.melskens@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.JuridischeRegelVoorIedereenHal;

/**
 * ActiviteitEmbedded
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-20T08:14:08.057894Z[Etc/UTC]")
public class ActiviteitEmbedded {
  public static final String SERIALIZED_NAME_JURIDISCHE_REGELS_VOOR_IEDEREEN = "juridischeRegelsVoorIedereen";
  @SerializedName(SERIALIZED_NAME_JURIDISCHE_REGELS_VOOR_IEDEREEN)
  private List<JuridischeRegelVoorIedereenHal> juridischeRegelsVoorIedereen = null;


  public ActiviteitEmbedded juridischeRegelsVoorIedereen(List<JuridischeRegelVoorIedereenHal> juridischeRegelsVoorIedereen) {
    
    this.juridischeRegelsVoorIedereen = juridischeRegelsVoorIedereen;
    return this;
  }

  public ActiviteitEmbedded addJuridischeRegelsVoorIedereenItem(JuridischeRegelVoorIedereenHal juridischeRegelsVoorIedereenItem) {
    if (this.juridischeRegelsVoorIedereen == null) {
      this.juridischeRegelsVoorIedereen = new ArrayList<>();
    }
    this.juridischeRegelsVoorIedereen.add(juridischeRegelsVoorIedereenItem);
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;Bij een regel die een activiteit vastlegt geeft deze relatie aan om welke activiteit het gaat. De bijbehorende locatie(s) waar het om gaat is/zijn bij de activiteit zelf te vinden.&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;p&gt;Een inhoudelijke toelichting op de toepassing van het informatie-element.&lt;/p&gt;&lt;/body&gt;
   * @return juridischeRegelsVoorIedereen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<body><p>Bij een regel die een activiteit vastlegt geeft deze relatie aan om welke activiteit het gaat. De bijbehorende locatie(s) waar het om gaat is/zijn bij de activiteit zelf te vinden.</p></body><body><p>Een inhoudelijke toelichting op de toepassing van het informatie-element.</p></body>")

  public List<JuridischeRegelVoorIedereenHal> getJuridischeRegelsVoorIedereen() {
    return juridischeRegelsVoorIedereen;
  }


  public void setJuridischeRegelsVoorIedereen(List<JuridischeRegelVoorIedereenHal> juridischeRegelsVoorIedereen) {
    this.juridischeRegelsVoorIedereen = juridischeRegelsVoorIedereen;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActiviteitEmbedded activiteitEmbedded = (ActiviteitEmbedded) o;
    return Objects.equals(this.juridischeRegelsVoorIedereen, activiteitEmbedded.juridischeRegelsVoorIedereen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(juridischeRegelsVoorIedereen);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActiviteitEmbedded {\n");
    sb.append("    juridischeRegelsVoorIedereen: ").append(toIndentedString(juridischeRegelsVoorIedereen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

