/*
 * Plan SW - Toepasbare regel SW
 * Nog in te voorzien
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: robert.melskens@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GeometrieType;
import org.openapitools.client.model.Locatie;
import org.openapitools.client.model.LocatieHalAllOf;
import org.openapitools.client.model.LocatieLinks;
import org.openapitools.client.model.LocatieType;
import org.openapitools.client.model.WaardeEenheid;

/**
 * LocatieHal
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-02-10T09:19:26.366Z[Etc/UTC]")
public class LocatieHal {
  public static final String SERIALIZED_NAME_BEGINDATUM = "begindatum";
  @SerializedName(SERIALIZED_NAME_BEGINDATUM)
  private LocalDate begindatum;

  public static final String SERIALIZED_NAME_EINDDATUM = "einddatum";
  @SerializedName(SERIALIZED_NAME_EINDDATUM)
  private LocalDate einddatum;

  public static final String SERIALIZED_NAME_GEOMETRIE = "geometrie";
  @SerializedName(SERIALIZED_NAME_GEOMETRIE)
  private String geometrie;

  public static final String SERIALIZED_NAME_GEOMETRIE_BRON = "geometrieBron";
  @SerializedName(SERIALIZED_NAME_GEOMETRIE_BRON)
  private String geometrieBron;

  public static final String SERIALIZED_NAME_GEOMETRIE_TYPE = "geometrieType";
  @SerializedName(SERIALIZED_NAME_GEOMETRIE_TYPE)
  private GeometrieType geometrieType;

  public static final String SERIALIZED_NAME_HOOGTE = "hoogte";
  @SerializedName(SERIALIZED_NAME_HOOGTE)
  private WaardeEenheid hoogte;

  public static final String SERIALIZED_NAME_IDENTIFICATIE = "identificatie";
  @SerializedName(SERIALIZED_NAME_IDENTIFICATIE)
  private String identificatie;

  public static final String SERIALIZED_NAME_NOEMER = "noemer";
  @SerializedName(SERIALIZED_NAME_NOEMER)
  private String noemer;

  public static final String SERIALIZED_NAME_OMVATTENDE_LOCATIE_IDENTIFICATIES = "omvattendeLocatieIdentificaties";
  @SerializedName(SERIALIZED_NAME_OMVATTENDE_LOCATIE_IDENTIFICATIES)
  private List<String> omvattendeLocatieIdentificaties = null;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private LocatieType type;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private LocatieLinks links;


  public LocatieHal begindatum(LocalDate begindatum) {
    
    this.begindatum = begindatum;
    return this;
  }

   /**
   * Get begindatum
   * @return begindatum
  **/
  @ApiModelProperty(required = true, value = "")

  public LocalDate getBegindatum() {
    return begindatum;
  }


  public void setBegindatum(LocalDate begindatum) {
    this.begindatum = begindatum;
  }


  public LocatieHal einddatum(LocalDate einddatum) {
    
    this.einddatum = einddatum;
    return this;
  }

   /**
   * Get einddatum
   * @return einddatum
  **/
  @ApiModelProperty(required = true, value = "")

  public LocalDate getEinddatum() {
    return einddatum;
  }


  public void setEinddatum(LocalDate einddatum) {
    this.einddatum = einddatum;
  }


  public LocatieHal geometrie(String geometrie) {
    
    this.geometrie = geometrie;
    return this;
  }

   /**
   * Get geometrie
   * @return geometrie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGeometrie() {
    return geometrie;
  }


  public void setGeometrie(String geometrie) {
    this.geometrie = geometrie;
  }


  public LocatieHal geometrieBron(String geometrieBron) {
    
    this.geometrieBron = geometrieBron;
    return this;
  }

   /**
   * Get geometrieBron
   * @return geometrieBron
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGeometrieBron() {
    return geometrieBron;
  }


  public void setGeometrieBron(String geometrieBron) {
    this.geometrieBron = geometrieBron;
  }


  public LocatieHal geometrieType(GeometrieType geometrieType) {
    
    this.geometrieType = geometrieType;
    return this;
  }

   /**
   * Get geometrieType
   * @return geometrieType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GeometrieType getGeometrieType() {
    return geometrieType;
  }


  public void setGeometrieType(GeometrieType geometrieType) {
    this.geometrieType = geometrieType;
  }


  public LocatieHal hoogte(WaardeEenheid hoogte) {
    
    this.hoogte = hoogte;
    return this;
  }

   /**
   * Get hoogte
   * @return hoogte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WaardeEenheid getHoogte() {
    return hoogte;
  }


  public void setHoogte(WaardeEenheid hoogte) {
    this.hoogte = hoogte;
  }


  public LocatieHal identificatie(String identificatie) {
    
    this.identificatie = identificatie;
    return this;
  }

   /**
   * Get identificatie
   * @return identificatie
  **/
  @ApiModelProperty(required = true, value = "")

  public String getIdentificatie() {
    return identificatie;
  }


  public void setIdentificatie(String identificatie) {
    this.identificatie = identificatie;
  }


  public LocatieHal noemer(String noemer) {
    
    this.noemer = noemer;
    return this;
  }

   /**
   * Get noemer
   * @return noemer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNoemer() {
    return noemer;
  }


  public void setNoemer(String noemer) {
    this.noemer = noemer;
  }


  public LocatieHal omvattendeLocatieIdentificaties(List<String> omvattendeLocatieIdentificaties) {
    
    this.omvattendeLocatieIdentificaties = omvattendeLocatieIdentificaties;
    return this;
  }

  public LocatieHal addOmvattendeLocatieIdentificatiesItem(String omvattendeLocatieIdentificatiesItem) {
    if (this.omvattendeLocatieIdentificaties == null) {
      this.omvattendeLocatieIdentificaties = new ArrayList<>();
    }
    this.omvattendeLocatieIdentificaties.add(omvattendeLocatieIdentificatiesItem);
    return this;
  }

   /**
   * Get omvattendeLocatieIdentificaties
   * @return omvattendeLocatieIdentificaties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getOmvattendeLocatieIdentificaties() {
    return omvattendeLocatieIdentificaties;
  }


  public void setOmvattendeLocatieIdentificaties(List<String> omvattendeLocatieIdentificaties) {
    this.omvattendeLocatieIdentificaties = omvattendeLocatieIdentificaties;
  }


  public LocatieHal type(LocatieType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public LocatieType getType() {
    return type;
  }


  public void setType(LocatieType type) {
    this.type = type;
  }


  public LocatieHal links(LocatieLinks links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocatieLinks getLinks() {
    return links;
  }


  public void setLinks(LocatieLinks links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocatieHal locatieHal = (LocatieHal) o;
    return Objects.equals(this.begindatum, locatieHal.begindatum) &&
        Objects.equals(this.einddatum, locatieHal.einddatum) &&
        Objects.equals(this.geometrie, locatieHal.geometrie) &&
        Objects.equals(this.geometrieBron, locatieHal.geometrieBron) &&
        Objects.equals(this.geometrieType, locatieHal.geometrieType) &&
        Objects.equals(this.hoogte, locatieHal.hoogte) &&
        Objects.equals(this.identificatie, locatieHal.identificatie) &&
        Objects.equals(this.noemer, locatieHal.noemer) &&
        Objects.equals(this.omvattendeLocatieIdentificaties, locatieHal.omvattendeLocatieIdentificaties) &&
        Objects.equals(this.type, locatieHal.type) &&
        Objects.equals(this.links, locatieHal.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(begindatum, einddatum, geometrie, geometrieBron, geometrieType, hoogte, identificatie, noemer, omvattendeLocatieIdentificaties, type, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocatieHal {\n");
    sb.append("    begindatum: ").append(toIndentedString(begindatum)).append("\n");
    sb.append("    einddatum: ").append(toIndentedString(einddatum)).append("\n");
    sb.append("    geometrie: ").append(toIndentedString(geometrie)).append("\n");
    sb.append("    geometrieBron: ").append(toIndentedString(geometrieBron)).append("\n");
    sb.append("    geometrieType: ").append(toIndentedString(geometrieType)).append("\n");
    sb.append("    hoogte: ").append(toIndentedString(hoogte)).append("\n");
    sb.append("    identificatie: ").append(toIndentedString(identificatie)).append("\n");
    sb.append("    noemer: ").append(toIndentedString(noemer)).append("\n");
    sb.append("    omvattendeLocatieIdentificaties: ").append(toIndentedString(omvattendeLocatieIdentificaties)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

