/*
 * Plan SW - Toepasbare regel SW
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: robert.melskens@vng.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GeoJSONGeometrie;
import org.openapitools.client.model.LocatieType;

/**
 * &lt;body&gt;&lt;p&gt;Duiding van een geografische positie. Indien er naar een locatie verwezen wordt vanuit een BevoegdGezag dan betreft dit een ambtsgebied.&lt;/p&gt;&lt;/body&gt;
 */
@ApiModel(description = "<body><p>Duiding van een geografische positie. Indien er naar een locatie verwezen wordt vanuit een BevoegdGezag dan betreft dit een ambtsgebied.</p></body>")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-20T08:14:08.057894Z[Etc/UTC]")
public class Locatie {
  public static final String SERIALIZED_NAME_BEGINDATUM = "begindatum";
  @SerializedName(SERIALIZED_NAME_BEGINDATUM)
  private LocalDate begindatum;

  public static final String SERIALIZED_NAME_EINDDATUM = "einddatum";
  @SerializedName(SERIALIZED_NAME_EINDDATUM)
  private LocalDate einddatum;

  public static final String SERIALIZED_NAME_GEOMETRIE = "geometrie";
  @SerializedName(SERIALIZED_NAME_GEOMETRIE)
  private GeoJSONGeometrie geometrie;

  public static final String SERIALIZED_NAME_GEOMETRIE_BRON = "geometrieBron";
  @SerializedName(SERIALIZED_NAME_GEOMETRIE_BRON)
  private String geometrieBron;

  public static final String SERIALIZED_NAME_IDENTIFICATIE = "identificatie";
  @SerializedName(SERIALIZED_NAME_IDENTIFICATIE)
  private String identificatie;

  public static final String SERIALIZED_NAME_NOEMER = "noemer";
  @SerializedName(SERIALIZED_NAME_NOEMER)
  private String noemer;

  public static final String SERIALIZED_NAME_OMVATTENDE_LOCATIE_IDENTIFICATIES = "omvattendeLocatieIdentificaties";
  @SerializedName(SERIALIZED_NAME_OMVATTENDE_LOCATIE_IDENTIFICATIES)
  private List<String> omvattendeLocatieIdentificaties = null;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private LocatieType type;

  public static final String SERIALIZED_NAME_WERKPAKKET_CODE = "werkpakketCode";
  @SerializedName(SERIALIZED_NAME_WERKPAKKET_CODE)
  private String werkpakketCode;


  public Locatie begindatum(LocalDate begindatum) {
    
    this.begindatum = begindatum;
    return this;
  }

   /**
   * Get begindatum
   * @return begindatum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getBegindatum() {
    return begindatum;
  }


  public void setBegindatum(LocalDate begindatum) {
    this.begindatum = begindatum;
  }


  public Locatie einddatum(LocalDate einddatum) {
    
    this.einddatum = einddatum;
    return this;
  }

   /**
   * Get einddatum
   * @return einddatum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getEinddatum() {
    return einddatum;
  }


  public void setEinddatum(LocalDate einddatum) {
    this.einddatum = einddatum;
  }


  public Locatie geometrie(GeoJSONGeometrie geometrie) {
    
    this.geometrie = geometrie;
    return this;
  }

   /**
   * Get geometrie
   * @return geometrie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GeoJSONGeometrie getGeometrie() {
    return geometrie;
  }


  public void setGeometrie(GeoJSONGeometrie geometrie) {
    this.geometrie = geometrie;
  }


  public Locatie geometrieBron(String geometrieBron) {
    
    this.geometrieBron = geometrieBron;
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;De bron die is gebruikt voor, dan wel de wijze van inwinning van de geometrie.&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;p&gt;De bron die is gebruikt voor, dan wel de wijze van inwinning van de geometrie.&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;p&gt;De bron die is gebruikt voor, dan wel de wijze van inwinning van de geometrie.&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;p&gt;Een inhoudelijke toelichting op de toepassing van het informatie-element.&lt;/p&gt;&lt;/body&gt;
   * @return geometrieBron
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<body><p>De bron die is gebruikt voor, dan wel de wijze van inwinning van de geometrie.</p></body><body><p>De bron die is gebruikt voor, dan wel de wijze van inwinning van de geometrie.</p></body><body><p>De bron die is gebruikt voor, dan wel de wijze van inwinning van de geometrie.</p></body><body><p>Een inhoudelijke toelichting op de toepassing van het informatie-element.</p></body>")

  public String getGeometrieBron() {
    return geometrieBron;
  }


  public void setGeometrieBron(String geometrieBron) {
    this.geometrieBron = geometrieBron;
  }


  public Locatie identificatie(String identificatie) {
    
    this.identificatie = identificatie;
    return this;
  }

   /**
   * Get identificatie
   * @return identificatie
  **/
  @ApiModelProperty(required = true, value = "")

  public String getIdentificatie() {
    return identificatie;
  }


  public void setIdentificatie(String identificatie) {
    this.identificatie = identificatie;
  }


  public Locatie noemer(String noemer) {
    
    this.noemer = noemer;
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;Tekstuele beschrijving van een Locatie, zodat er als zodanig over deze locatie gesproken kan worden. De beschrijving kan een bepaalde naam zijn waaronder de Locatie bekend staat, maar (lang) niet elke Locatie heef een naam.&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;p&gt;Bijvoorbeeld het hele werkingsgebied van bevoegd gezag, zoals &#39;Het Koninkrijk der Nederlanden&#39; of gemeente &#39;Amersfoort&#39;. Bijvoorbeeld een natuurgebied zoals de &#39;Veluwe&#39; of de rivier de &#39;Rijn&#39; of het centrum van een woonplaats &#39;centrum Apeldoorn&#39;.&lt;/p&gt;&lt;/body&gt;
   * @return noemer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<body><p>Tekstuele beschrijving van een Locatie, zodat er als zodanig over deze locatie gesproken kan worden. De beschrijving kan een bepaalde naam zijn waaronder de Locatie bekend staat, maar (lang) niet elke Locatie heef een naam.</p></body><body><p>Bijvoorbeeld het hele werkingsgebied van bevoegd gezag, zoals 'Het Koninkrijk der Nederlanden' of gemeente 'Amersfoort'. Bijvoorbeeld een natuurgebied zoals de 'Veluwe' of de rivier de 'Rijn' of het centrum van een woonplaats 'centrum Apeldoorn'.</p></body>")

  public String getNoemer() {
    return noemer;
  }


  public void setNoemer(String noemer) {
    this.noemer = noemer;
  }


  public Locatie omvattendeLocatieIdentificaties(List<String> omvattendeLocatieIdentificaties) {
    
    this.omvattendeLocatieIdentificaties = omvattendeLocatieIdentificaties;
    return this;
  }

  public Locatie addOmvattendeLocatieIdentificatiesItem(String omvattendeLocatieIdentificatiesItem) {
    if (this.omvattendeLocatieIdentificaties == null) {
      this.omvattendeLocatieIdentificaties = new ArrayList<>();
    }
    this.omvattendeLocatieIdentificaties.add(omvattendeLocatieIdentificatiesItem);
    return this;
  }

   /**
   * Get omvattendeLocatieIdentificaties
   * @return omvattendeLocatieIdentificaties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getOmvattendeLocatieIdentificaties() {
    return omvattendeLocatieIdentificaties;
  }


  public void setOmvattendeLocatieIdentificaties(List<String> omvattendeLocatieIdentificaties) {
    this.omvattendeLocatieIdentificaties = omvattendeLocatieIdentificaties;
  }


  public Locatie type(LocatieType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public LocatieType getType() {
    return type;
  }


  public void setType(LocatieType type) {
    this.type = type;
  }


  public Locatie werkpakketCode(String werkpakketCode) {
    
    this.werkpakketCode = werkpakketCode;
    return this;
  }

   /**
   * &lt;body&gt;&lt;p&gt;Een unieke aanduiding van de verzameling samenhangende activiteiten gericht op het publiceren van een nieuwe versie van een omgevingsdocument.&lt;/p&gt;&lt;/body&gt;&lt;body&gt;&lt;p&gt;Er kunnen tegelijkertijd meerdere trajecten gaande zijn waarin bijvoorbeeld een omgevingsplan gewijzigd wordt, die elk leiden tot een apart te publiceren nieuwe versie van het omgevingsplan. De werkpakketcode biedt de mogelijkheid om de regelteksten te markeren die betrokken zijn in zo&#39;n traject. Daarvan kan gebruik gemaakt worden om alleen de regels  met bijhorende annotaties op te vragen voor een specifiek werkpakket. &lt;/p&gt;&lt;/body&gt;
   * @return werkpakketCode
  **/
  @ApiModelProperty(required = true, value = "<body><p>Een unieke aanduiding van de verzameling samenhangende activiteiten gericht op het publiceren van een nieuwe versie van een omgevingsdocument.</p></body><body><p>Er kunnen tegelijkertijd meerdere trajecten gaande zijn waarin bijvoorbeeld een omgevingsplan gewijzigd wordt, die elk leiden tot een apart te publiceren nieuwe versie van het omgevingsplan. De werkpakketcode biedt de mogelijkheid om de regelteksten te markeren die betrokken zijn in zo'n traject. Daarvan kan gebruik gemaakt worden om alleen de regels  met bijhorende annotaties op te vragen voor een specifiek werkpakket. </p></body>")

  public String getWerkpakketCode() {
    return werkpakketCode;
  }


  public void setWerkpakketCode(String werkpakketCode) {
    this.werkpakketCode = werkpakketCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Locatie locatie = (Locatie) o;
    return Objects.equals(this.begindatum, locatie.begindatum) &&
        Objects.equals(this.einddatum, locatie.einddatum) &&
        Objects.equals(this.geometrie, locatie.geometrie) &&
        Objects.equals(this.geometrieBron, locatie.geometrieBron) &&
        Objects.equals(this.identificatie, locatie.identificatie) &&
        Objects.equals(this.noemer, locatie.noemer) &&
        Objects.equals(this.omvattendeLocatieIdentificaties, locatie.omvattendeLocatieIdentificaties) &&
        Objects.equals(this.type, locatie.type) &&
        Objects.equals(this.werkpakketCode, locatie.werkpakketCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(begindatum, einddatum, geometrie, geometrieBron, identificatie, noemer, omvattendeLocatieIdentificaties, type, werkpakketCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Locatie {\n");
    sb.append("    begindatum: ").append(toIndentedString(begindatum)).append("\n");
    sb.append("    einddatum: ").append(toIndentedString(einddatum)).append("\n");
    sb.append("    geometrie: ").append(toIndentedString(geometrie)).append("\n");
    sb.append("    geometrieBron: ").append(toIndentedString(geometrieBron)).append("\n");
    sb.append("    identificatie: ").append(toIndentedString(identificatie)).append("\n");
    sb.append("    noemer: ").append(toIndentedString(noemer)).append("\n");
    sb.append("    omvattendeLocatieIdentificaties: ").append(toIndentedString(omvattendeLocatieIdentificaties)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    werkpakketCode: ").append(toIndentedString(werkpakketCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

