"""
    Plan SW - Toepasbare regel SW

    Nog in te voorzien  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: robert.melskens@vng.nl
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.api_client import ApiClient, Endpoint as _Endpoint
from openapi_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from openapi_client.model.bad_request_foutbericht import BadRequestFoutbericht
from openapi_client.model.foutbericht import Foutbericht
from openapi_client.model.regeltekst_hal import RegeltekstHal
from openapi_client.model.regeltekst_hal_collectie import RegeltekstHalCollectie


class RegeltekstenApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __getregeltekst(
            self,
            identificatie,
            **kwargs
        ):
            """getregeltekst  # noqa: E501

            <body><p>Het bericht dat de JSON/REST API voor het ophalen van gegevens van een amendement retourneert.</p></body>  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.getregeltekst(identificatie, async_req=True)
            >>> result = thread.get()

            Args:
                identificatie (str): <body><p>De unieke identificatie waaronder elk object van dit type bekend is.</p></body>

            Keyword Args:
                expand (str): Hiermee kun je opgeven welke gerelateerde resources meegeleverd moeten worden, en hun inhoud naar behoefte aanpassen. Hele resources of enkele properties geef je in de expand parameter kommagescheiden op. Properties die je wil ontvangen geef je op met de resource-naam gevolgd door de property naam, met daartussen een punt. In de definitie van het antwoord kun je bij _embedded zien welke gerelateerde resources meegeleverd kunnen worden. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/expand.feature).. [optional]
                inclusiefvervallen (bool): <body><p>Als de parameter 'vanafdatum' een waarde heeft dan moet een evt. waarde van dit attribute worden genegeerd.</p></body>. [optional]
                vanafdatum (date): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                RegeltekstHal
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['identificatie'] = \
                identificatie
            return self.call_with_http_info(**kwargs)

        self.getregeltekst = _Endpoint(
            settings={
                'response_type': (RegeltekstHal,),
                'auth': [],
                'endpoint_path': '/regelteksten/{identificatie}',
                'operation_id': 'getregeltekst',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'identificatie',
                    'expand',
                    'inclusiefvervallen',
                    'vanafdatum',
                ],
                'required': [
                    'identificatie',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'identificatie':
                        (str,),
                    'expand':
                        (str,),
                    'inclusiefvervallen':
                        (bool,),
                    'vanafdatum':
                        (date,),
                },
                'attribute_map': {
                    'identificatie': 'identificatie',
                    'expand': 'expand',
                    'inclusiefvervallen': 'inclusiefvervallen',
                    'vanafdatum': 'vanafdatum',
                },
                'location_map': {
                    'identificatie': 'path',
                    'expand': 'query',
                    'inclusiefvervallen': 'query',
                    'vanafdatum': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/hal+json',
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__getregeltekst
        )

        def __getregelteksten(
            self,
            **kwargs
        ):
            """getregelteksten  # noqa: E501

            <body><p>Het bericht dat de JSON/REST API voor het ophalen van een collectie amendementen retourneert.</p></body>  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.getregelteksten(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                page (int): Een pagina binnen de gepagineerde resultatenset.. [optional]
                expand (str): Hiermee kun je opgeven welke gerelateerde resources meegeleverd moeten worden, en hun inhoud naar behoefte aanpassen. Hele resources of enkele properties geef je in de expand parameter kommagescheiden op. Properties die je wil ontvangen geef je op met de resource-naam gevolgd door de property naam, met daartussen een punt. In de definitie van het antwoord kun je bij _embedded zien welke gerelateerde resources meegeleverd kunnen worden. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/expand.feature).. [optional]
                begindatum (date): [optional]
                codebevoegdgezag (str): <body><p>Een inhoudelijke toelichting op de toepassing van het informatie-element.</p></body>. [optional]
                documentidentificatie (str): <body><p>Een inhoudelijke toelichting op de toepassing van het informatie-element.</p></body>. [optional]
                documentopschrift (str): <body><p>Een inhoudelijke toelichting op de toepassing van het informatie-element.</p></body>. [optional]
                einddatum (date): [optional]
                gerelateerderegeltekstidentificaties (str): [optional]
                inclusiefvervallen (bool): <body><p>Als de parameter 'vanafdatum' een waarde heeft dan moet een evt. waarde van dit attribute worden genegeerd.</p></body>. [optional]
                koplabel (str): <body><p>Een inhoudelijke toelichting op de toepassing van het informatie-element.</p></body>. [optional]
                kopnummer (str): <body><p>Een inhoudelijke toelichting op de toepassing van het informatie-element.</p></body>. [optional]
                kopopschrift (str): <body><p>Een inhoudelijke toelichting op de toepassing van het informatie-element.</p></body>. [optional]
                laatstewijzigingsdatum (date): [optional]
                locatieidentificaties (str): [optional]
                omschrijving (str): <body><p>De letterlijke tekst waarmee de Regeltekst is omschreven, in een artikel of een lid. Een Regeltekst is altijd Ã©Ã©n doorlopend stuk juridische tekst, welke juridische regels bevat.</p></body>. [optional]
                vanafdatum (date): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                RegeltekstHalCollectie
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.getregelteksten = _Endpoint(
            settings={
                'response_type': (RegeltekstHalCollectie,),
                'auth': [],
                'endpoint_path': '/regelteksten',
                'operation_id': 'getregelteksten',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'page',
                    'expand',
                    'begindatum',
                    'codebevoegdgezag',
                    'documentidentificatie',
                    'documentopschrift',
                    'einddatum',
                    'gerelateerderegeltekstidentificaties',
                    'inclusiefvervallen',
                    'koplabel',
                    'kopnummer',
                    'kopopschrift',
                    'laatstewijzigingsdatum',
                    'locatieidentificaties',
                    'omschrijving',
                    'vanafdatum',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'page',
                ]
            },
            root_map={
                'validations': {
                    ('page',): {

                        'inclusive_minimum': 1,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'page':
                        (int,),
                    'expand':
                        (str,),
                    'begindatum':
                        (date,),
                    'codebevoegdgezag':
                        (str,),
                    'documentidentificatie':
                        (str,),
                    'documentopschrift':
                        (str,),
                    'einddatum':
                        (date,),
                    'gerelateerderegeltekstidentificaties':
                        (str,),
                    'inclusiefvervallen':
                        (bool,),
                    'koplabel':
                        (str,),
                    'kopnummer':
                        (str,),
                    'kopopschrift':
                        (str,),
                    'laatstewijzigingsdatum':
                        (date,),
                    'locatieidentificaties':
                        (str,),
                    'omschrijving':
                        (str,),
                    'vanafdatum':
                        (date,),
                },
                'attribute_map': {
                    'page': 'page',
                    'expand': 'expand',
                    'begindatum': 'begindatum',
                    'codebevoegdgezag': 'codebevoegdgezag',
                    'documentidentificatie': 'documentidentificatie',
                    'documentopschrift': 'documentopschrift',
                    'einddatum': 'einddatum',
                    'gerelateerderegeltekstidentificaties': 'gerelateerderegeltekstidentificaties',
                    'inclusiefvervallen': 'inclusiefvervallen',
                    'koplabel': 'koplabel',
                    'kopnummer': 'kopnummer',
                    'kopopschrift': 'kopopschrift',
                    'laatstewijzigingsdatum': 'laatstewijzigingsdatum',
                    'locatieidentificaties': 'locatieidentificaties',
                    'omschrijving': 'omschrijving',
                    'vanafdatum': 'vanafdatum',
                },
                'location_map': {
                    'page': 'query',
                    'expand': 'query',
                    'begindatum': 'query',
                    'codebevoegdgezag': 'query',
                    'documentidentificatie': 'query',
                    'documentopschrift': 'query',
                    'einddatum': 'query',
                    'gerelateerderegeltekstidentificaties': 'query',
                    'inclusiefvervallen': 'query',
                    'koplabel': 'query',
                    'kopnummer': 'query',
                    'kopopschrift': 'query',
                    'laatstewijzigingsdatum': 'query',
                    'locatieidentificaties': 'query',
                    'omschrijving': 'query',
                    'vanafdatum': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/hal+json',
                    'application/problem+json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__getregelteksten
        )
